### ISSUE TITLE
pv  - Pipe Viewer - update request

### ISSUE THREAD

**Issue by ophian** [solus-packages/pv#1]
Hi there,

pv - Pipe Viewer - is a terminal-based tool for monitoring the progress of data through a pipeline.
    
Last update by rapenne-s and JoshStrobl Update pv to 1.6.20 on Nov 9, 2021
https://github.com/solus-packages/pv/commit/90a7188f811942420f9af2876bae3180809b9856

but current version is: 1.7.24 (30 July 2023)
https://www.ivarch.com/programs/pv.shtml

Is there a reason why 1.7 versions were not pulled for solus since two years?
    
Is it because of a missing maintainer? Might @silkeh Silke Hofstra take over since having already contributed?
Or isn't it worth having it supported since dd cloning can use with progress bar?

Thanks

PS. I could not ask this in getsolus discuss forum since I cannot log-in. My old account from 2019 won't let me in and the login popup is reacting strange...

PPS. @EbonJaeger
 It surely is the wrong place to ask this, but I did not know where else because of that flarum issue.
 Please delete it when having noticed or having mentioned/answered this in flarum.

**Comment by silkeh** [comment]
> Is there a reason why 1.7 versions were not pulled for solus since two years?

The project being active again probably flew under the radar. I don't see any reason not to update it.

> Is it because of a missing maintainer? Might @silkeh take over since having already contributed?

Seems easy enough, so sure! :slightly_smiling_face: 

The update will be included in the next sync!

> It surely is the wrong place to ask this, but I did not know where else because of that flarum issue.

@ophian the correct place to open issues is [getsolus/packages](https://github.com/getsolus/packages/), but don't worry about it!

> PS. I could not ask this in getsolus discuss forum since I cannot log-in. My old account from 2019 won't let me in and the login popup is reacting strange...

Please try to reach out [on Matrix](https://matrix.to/#/#solus-support:matrix.org), we might be able to help you with your forum-account there.

**Comment by ophian** [comment]
Yepp, thanks. Found the link for package requests later myself but then I could not delete my issue post here and did not want to double post.
About Matrix and my forum account I will first need to find out how to use it... I'll see...
